language: python
python:
  - "3.6"
env:
  - TOXENV=django111-py27
  - TOXENV=django111-py35
  - TOXENV=django20-py35
  - TOXENV=django225-py36

install:
  - pip install tox

script: tox

after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: praekelt.org
  password:
    secure: vd7EJcZekx4ws2cwEatVHjP7/GqY7S+f9vjtj34LN9I1TU2579W021BJrHDEeX/+mFuZfjcVDkDfm5l7oVKpUgweb3Zv1iHoRHAayh9qEgnf2wLOpETLqbVx/pNQvLOJaMLJ9BYvYt8xdLN9WD2gegGQ7uBe1dhZ9pWyI5yitFVzvo/uZNZ0TNYIhlu/2OtTgOU/dwWHkaFRDbp8HsAhKmbf5AfZhyrgAtO4UobvvX6KlwvFeK/K7p8JQo5M7o3OZYicmhOPWiC12ucE3N2NkpX3TnMYUt3r5oACd450awBn47Wn0HVZp16nfHe8FA2jrTrGNYsKlWt0J/G3SRTMI939ywNrhVLsifD5bv4dgUsJysFIavgpRNI8bz2oWJnmqfVPsWStY2Aj2/LnwzVZCeF+yPzryn+CQ+iNE1/l7l1g9cH1TDUlP0mugdszV++lP8W4kIIV55m12ECAQFRKki7Um80V7OOGyUAJI75AT1XvhFwBCS+BwSHD3HN6C/JUa7gywZSOHFyw9BToqbF3gSERSoHYfeqXUCDKkvLJLfJPMxO8OkAhb+xdGO/ZLpFuKA61H8v6+d1Gm6BJbWQyyfqGVuu8vNmgbgwCC5Fk5UaIRdmdGZN1PfxszOn1FNfhsMvC8uyXdmRNazHZlKOs6IWRGSqjXu67/ejMGLwFz1o=
  on:
    tags: true
    python: 3.6
