language: python
python:
  - "3.6"
env:
  - TOXENV=django111-py27
  - TOXENV=django111-py35
  - TOXENV=django20-py35
  - TOXENV=django225-py36

install:
  - pip install tox

script: tox

after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: praekelt.org
  password:
    secure: UMzofXMie684edH4aFppeymRNXN9knyF9lVHe8io6TERXG3Nel0MQBpUTtErT1lRnc2bKJ4Vbdua7Z3y6i3U1pFoVdgIjjr0estcuPg9aepFbzbQoVeEFPG4/02iWI28yrdl8040Sh9pxt0Gz10A9H7EiVJ3j9ttNfFdwGV2as9ZVyN7YAN6CKGBsGA7XHvd+fBpmqWqGVzYPufUImGIiXKX2hjzJvd6+G1mzPtFfVLFwA5phODw9MemDsSzm94vm33HX2ecaHfz5XzRK0EkF3Zm98tEl5kVFk3Y2/eK37QxjP8KdfQD8KvnUbcBNvFPIHh7nG70HOEPWp+i4wqesPTBy/8oNDGleBXLhDLgSYsOQIfNgfBtp81SUnnatcSc4QiAieS1hgEDuVo8//mvBsunpBL7P6sEmuw/3qswUlLWXBvDs0F9edDSuvO2rRTUQ2JYYkN8EZkPS1i62hVUz+C9D9nKkfGr0A6mN3QikDb0F17FLLXJpO2sU4Aj0khWNxChU5N6kmVy0GW3MTBNJAZqkEvjwx/vcQTIozkIl3UNZwUynqRWQFtYIbGlYDFPtr6YJj2D2usVLORC3OfCHmXFsLMwgt873lZvSAn9/G56iRi03vj3V4TprEvCNuha5Ai7t5dZIs+vqqzYm20lKJfidB/xnoh0gQhHJbvgwkc=
  on:
    tags: true
    python: 3.6
