language: python
python:
  - "3.6"
env:
  - TOXENV=django111-py27
  - TOXENV=django111-py35
  - TOXENV=django20-py35
  - TOXENV=django225-py36

install:
  - pip install tox

script: tox

after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: incBNqD1WDloWPGc1+Te6NMr7sD880gBPAe/vugKSg6QMVD7Ai1C3JwN+dO+y8yI0E0TgjwkXl/CCBWDVfGpLskgZ/UcudRsAqr+2IducEwBeJFGiVp7j/UE8/JEjIG7CHkWWuAMr0fd3Dv2b0F1AaIqdpKvN3VLbKO7P8Eau0jxaWWIN9yNIXiS4q7pF7GYrpxiVWE7vWs66iD6SEQUIRmsSyI5VMxeOaWBKo+7MQJtIem6VyJWTxzF+aZ4A0TL2R57xSYd+es9XA7iW4iVsndeLfvC0Wlv4u9U74WHQ86nsSvQTnUEG6sMe9LlRlVva4NkuuA2ImPbhmzpw5v4xBLn1A1wvfS/NfTYhbR0RPUkEGuPS1dU+S7TUIKBNptcMYAsqstAVZQv+zY/cJfhedmqMmT3+22XZVUrjHa70SGpHfQ7/2qX9E9LVS5Brzd18ge6ciPZtF3gsujAjiVq0l7iHU2S+be/RHSniz9MzA0Hps5ai/ADE/lqwboxjtzLthRLfnjUU6zuOjEyGIEEZfXgbaC6uDh8W+EBBeHyOsD3+9+Mrvs33hjsw1TEUMU6y7Bv0wX7J3FXIqUdTyzq2XscpUQA0BzR6hPTuodFOJ3wkTq8+U8FYVxWflipkxXgeQEiYzCyD1GEgnd3GoGaKYvqaE5F4frcmoALohv8HXI=
  on:
    tags: true
    python: 3.6
