language: python
python:
  - "3.6"
env:
  - TOXENV=django111-py27
  - TOXENV=django111-py35
  - TOXENV=django20-py35
  - TOXENV=django225-py36

install:
  - pip install tox

script: tox

after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: praekelt.org
  password:
    secure: rnGNl3NRxGIXTDR+ZA0i8IBn5OyyvLsG3u+SJIWSqyAgPHEucbxBCRuhUN/fIhdTQZFFffQukojxaD4kZnTz13oWMbq/NU0LnofzWKLC59eeVIqzIFpYUVqyTw1gr9PjoeVI4m8bmW+DD/aVVHQKS6TOv98XnzGwVqOjf7sW3neu8a919YXIg47GUx+xh2/dkKSr+KgyqjkRJWcGODZPZ2ZyJmYWSKjCHTN/GkVShbAKykcXIvYUn/ebIYoAFb/OfYi/wzZ3Jy4Dg3Br0qhnROvMgumPCGPrVYPhOFKyUUhzIG2H0VgcwWUpQVGX7QwHqAHhOhjjvb7IvajXtWX4sSbtqncRm+71cqceYtoDVxh80GyHKdn1HPGIgAzgrMUu8vuc+35YpbfwW6mzd5sgRJPFTltfPi1ubA3rsFY6g29tguaX53XQNmxx/eotYkoZT4yZlnAY6TXwcvYgg5M8gJ50TIHjCwIyeje6WNLBVn8MMvg7d6f+aEAXvuWXi/WkQPGydHoD9El72vwSHwP4AX+J38mpUBi4ATqLg3UeYSY8yLg/DCT6DXpyPubEl0cDNAwDGeAVEPm5DxfoV10Qgf+wrtP7gx/HS5aWbrneAF/BmLEmzdDpl3BsDWfSzSU4L959budrAcC6mES+W9O1RbvYBfz8YOgWC9MNWsIRR4w=
  on:
    tags: true
    python: 3.6
