language: python
python:
  - "3.5"
env:
  - TOXENV=django111-py27
  - TOXENV=django111-py35
  - TOXENV=django20-py35

install:
  - pip install tox

script: tox

after_success:
  - coveralls

deploy:
  provider: pypi
  user: Praekelt
  password:
    # NOTE: See http://docs.travis-ci.com/user/encryption-keys/ for more info.
    secure: "insert encrypted pypi password here"
  on:
    tags: true
    all_branches: true