# Generate config files in /conf from these definitions
nginx:
    app_name: mote
    web_server_name: qa-kevro.za.prk-host.net
    primary_web_server_name: qa-kevro.za.prk-host.net
    mobi_server_name: m.qa-kevro.za.prk-host.net
    primary_mobi_server_name: m.qa-kevro.za.prk-host.net
    admin_server_name: qa-kevro.za.prk-host.net
    cookie_domain: .qa-kevro.za.prk-host.net
    port_prefix: 90

supervisor:
    app_name: mote
    port_prefix: 90
