options:
    formatter: stylish
files:
    include: 'project-source/fed-src/app/**/*.s+(a|c)ss'
rules:
    property-sort-order: 'smacss'
    placeholder-in-extend: 0
    indentation:
        - 1
        -
            size: 4
    nesting-depth:
        - 1
        -
            max-depth: 4
    no-duplicate-properties: 0
    mixins-before-declarations: 0
    property-sort-order: 'smacss'
    zero-unit:
        include: true
    quotes:
        - 1
        -
            style: 'double'
    no-color-literals:
        - 1
        -
            allow-rgba: true
    no-mergeable-selectors:
        - 1
        -
            whitelist: ['.objectfit', '.csstransforms', '.no-objectfit']
